### ISSUE TITLE
How an I extend JCR datastore which see from webdav?

### ISSUE THREAD

**Issue by lillianphyo** [exoplatform/exo-documentation#255]
![image](https://user-images.githubusercontent.com/19262583/87217082-b4c5cb80-c36b-11ea-9173-35a6275737d6.png)

please let me know how can I extend this file directory?

**Comment by ahamdi** [comment]
@lillianphyoe What do you mean by extending? Increasing the size of that drive?

**Comment by lillianphyo** [comment]
yes. I want to know how to extend that drive sincerely.

**Comment by lillianphyo** [comment]
anybody can you please help?

**Comment by lillianphyo** [comment]
Now I know. It show my drive C: partition.
