### ISSUE TITLE
how do can i skip Register Your Software URL Page on exoplatform ?

### ISSUE THREAD

**Issue by aungpaingoo** [exoplatform/exo-documentation#256]
how do can i skip this page ?
i want to reach directly to login page .
Please Help me. 
![Screenshot (184)](https://user-images.githubusercontent.com/67823925/88532804-39327280-d02b-11ea-870a-305fd4af1c8e.png)

**Comment by plamarque** [comment]
Software registration is mandatory see  https://docs.exoplatform.org/en/latest/Installation.html?#registering-your-software

You shouldn't need to do this more than once unless there is a problem on our end on the tribe. What happens when you click "Continue" ?

**Comment by aungpaingoo** [comment]
Yes,I click continue and than i reach login page but i login next time i reach in register page again. i want to skip that page when i login next time. I just want to skip that URL .
